# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://fluquid.github.io/ilen-tech/
title: iLen Technologies
email: info@ilen-tech.com
author: Anonymous
description: > # "Write an awesome description for your new site here. 
    iLen Tech Description
copyright: 'Copyright &copy; 2017 iLen Tech Ltd. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

include: ['_posts', '_features']
exclude: ['gems', 'vendor']
collections:
  - features

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

defaults:
  - 
    scope:
      path: ""
    values:
      layout: "default"

social:
  - title: twitter
    url: https://twitter.com/
  - title: github
    url: https://github.com/
  - title: linkedin
    url: https://www.linkedin.com/company/
  - title: email
    url: mailto:john@ilen-tech.com
    icon: envelope


plugins:
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-analytics
    - jekyll-twitter-plugin
